title: My Field Guide
description: A documentation of park research
baseurl: ""
url: ""

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post" 